### ISSUE TITLE
Breaking changes after updating extension to v3

### ISSUE THREAD

**Issue by j-dowell** [reduxjs/redux-devtools#1002]
After updating the Redux Dev Tools extension (Chrome) to v3 this weekend, our app is no longer working when the extension is enabled. Still works on Firefox as the add on hasn't been updated yet.

We use [redux-most](https://github.com/joshburgess/redux-most) as middleware, like so:

```js
import { createStore, compose, combineReducers } from 'redux'
import { combineEpics, createEpicMiddleware, createStateStreamEnhancer } from 'redux-most'

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

const epicMiddleware = createEpicMiddleware(
    combineEpics([
        appEpic,
        ... // other epics here
    ])
)

const store = createStore(
    combineReducers({
        appReducer,
        ... // other reducers here
    }),
    composeEnhancers(createStateStreamEnhancer(epicMiddleware))
)

export default store
````

And now when accessing state (using [withState](https://github.com/joshburgess/redux-most#withstate-statestream-actionstream)), instead of the regular state object being returned it looks something like this:
```js
{
    actionsById: {...},  
    committedState: undefined, 
    computedStates: [{...}],
    currentStateIndex: 1,
    isLocked: false,
    isPaused: false,
    monitorState: {},
    nextActionId: 2,
    skippedActionIds: [],  
    stagedActionIds: [0, 1, ...],
}
```

Where the actual state object can be located at the last index of `computedStates`

Does anyone have any ideas as to what happened here and how it could be resolved? Thanks

**Comment by markerikson** [comment]
Oh dear. 

A couple quick questions to get a sense of what's going on:

- What happens if you just `console.log(store.getState())`?  Is it also this "lifted state" value from the DevTools?
- What happens if you skip the `composeWithEnhancers` part?
- Finally, what about using `composeWithEnhancers` and skipping the middleware?

**Comment by Methuselah96** [comment]
@j-dowell I believe I have a solution. There was an observable property leaking through the Redux DevTools store that was exposing the lifted state.

However if I release the fix, I'm concerned that your app will break even worse. In my testing it seemed that `redux-most` could not handle Redux versions `>=4.1.0` due to the changes in how the observable symbol was ponyfilled. In those cases, the app white-screens and the same thing would happen if I released the fix.

What version of Redux are you currently on? If you're on a version less than `4.1.0` can you try updating and see if breaks your app?

**Comment by markerikson** [comment]
Huh. What's the observable ponyfill issue, specifically?

**Comment by Methuselah96** [comment]
Oh, I guess it's technically a polyfill for `Symbol.observable` if `Symbol` exists and a ponyfill otherwise. TIL

The issue is:
Redux 4.0.5 depends on `symbol-observable` as does `most`. `symbol-observable` [polyfills `Symbol.observable`](https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js#L22) and so it doesn't matter which one calls `symbol-observable` first, because the first one to access will do the polyfill and therefore both libraries will share the same symbol.

Redux 4.1.0 does not depend on `symbol-observable` and so if you import `redux` first, it sees that `Symbol.observable` is not set and decides to use the `@@observable` property. However when `most` calls `symbol-observable` later it polyfills `Symbol.observable` and returns that to `most`. Because of that the observable properties don't match up and `most` crashes because it was expecting the Redux store to have a `Symbol.observable` property.

So it seems like Redux should polyfill `Symbol.observable` if it wants to remain compatible with libraries that use `symbol-observable` (perhaps add back the dependency on `symbol-observable` for simplicity?).

**Comment by markerikson** [comment]
Grrr. We specifically removed that dependency in 4.1.0 specifically because it was a lousy 1-line dependency and I didn't want to have to rely on it.

Could we just advise users to import the polyfill first if it's a thing they need to depend on?

**Comment by Methuselah96** [comment]
Was the dependency causing any specific problems? It seems like adding a few bytes to the bundle size is easily worth it in this case in order to avoid the special instructions of having to import the polyfill first, any complications that arise from that, as well as any developer time spent trying to figure out why it's broken. It's a pretty bad gotcha and easily solved on the Redux side of things. I like getting rid of dependencies as much as the next person, but this one seems like a net positive.

**Comment by sorinpav** [comment]
Hi! Is there a way to downgrade to a previous version? We're having issues as well, and I'm not sure what to do to make it work again. We shouldn't have to make changes to our code just to use an extension..

**Comment by Methuselah96** [comment]
@sorinpav Unfortunately Chrome Extensions automatically updates extensions without consent and doesn't have a way to downgrade and  which is a severe limitation of Chrome Extensions. For now the best way to work around it is to download the `extension.zip` artifact from [the most recent release](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.17.0) and [load it unpacked](https://stackoverflow.com/a/24577660/5327429). Hopefully we can get this resolved as soon as possible.

Another possible workaround would be to try to `import $$observable from 'symbol-observable';` as the first import in your app. What version of Redux are you using?

**Comment by sorinpav** [comment]
Thank you so much! That sorted our redux devtools extension. It's really frustrating to see breaking changes like that, hopefully it gets sorted out soon. 

The redux version I'm using is 4.1.2.

**Comment by j-dowell** [comment]
> 



> @j-dowell I believe I have a solution. There was an observable property leaking through the Redux DevTools store that was exposing the lifted state.
> 
> However if I release the fix, I'm concerned that your app will break even worse. In my testing it seemed that `redux-most` could not handle Redux versions `>=4.1.0` due to the changes in how the observable symbol was ponyfilled. In those cases, the app white-screens and the same thing would happen if I released the fix.
> 
> What version of Redux are you currently on? If you're on a version less than `4.1.0` can you try updating and see if breaks your app?

Thanks for looking into it. But our app is already using `4.1.1` of redux with no issues.

**Comment by Methuselah96** [comment]
Thanks for the info. My guess is that the reason it breaks with the extension but not with plain Redux is because the order of import is the Redux DevTools extension, `most`/RxJS, and then Redux, however I haven't confirmed that for sure yet. I have a fix in mind that I'll try to get out today.

**Comment by Methuselah96** [comment]
@sorinpav Are you also using `redux-most`?

**Comment by sorinpav** [comment]
@Methuselah96 no, I'm not using any of that

**Comment by Methuselah96** [comment]
@sorinpav Got it, what problems are you having with the new extension?

**Comment by sorinpav** [comment]
@Methuselah96 the new extension just seems to not show any state whatsoever. I get state:undefined if I remember correctly. Maybe I haven't set things up properly, but the existence of this issue tells me I'm not the only one with this problem.

**Comment by a-c-sreedhar-reddy** [comment]
Hi @Methuselah96 
The internal object from redux is being returned in my case.

**Comment by Methuselah96** [comment]
@sorinpav Got it, sorry to hear you're having problems. This root issue of the OP is very distinctly caused by a weird interaction with symbol-observable and the extension that should only affect people who are using symbol-observable or a library that uses it like most.js. It's likely your root issue is different. If you could open a new issue with a description that shows the code you're using to set up your Redux store that would be extremely helpful. Thanks!

@a-c-sreedhar-reddy Sorry to hear that. Are you using any libraries that depend on symbol-observable and how can you show me the code you're using to set up your Redux store?

**Comment by Methuselah96** [comment]
@a-c-sreedhar-reddy Also, are you getting the internal object when calling `.getState()` or something else?

**Comment by sorinpav** [comment]
@Methuselah96 i will open something up tomorrow morning if that's ok! Once again, thank you for all your help tonight! I'll be back tomorrow!

**Comment by j-dowell** [comment]
@Methuselah96 Sure, just installed and it crashed with `Uncaught TypeError: from(x) must be observable, iterable, or array-like: [object Object]
`

**Comment by a-c-sreedhar-reddy** [comment]
> Are you using any libraries that depend on symbol-observable

Yes we added `import 'symbol-observable';`  in our polyfill.ts of our angular app.




> can you show me the code you're using to set up your Redux store


This is how we instantiate redux store.
```js
const composeEnhancers = composeWithDevTools(options);
export const globalStore = createStore(
  rootReducer,
  composeEnhancers(
    applyMiddleware(
      ...getDefaultMiddleware({
        thunk: true,
        immutableCheck: false,
        serializableCheck: false,
      }),
    ),
    // other store enhancers if any
  ),
);
```



> are you getting the internal object when calling `.getState()` or seeing it some other way?

We wrap store in a `from` from `rxjs` ie `from(globalStore)` and subscribing to this gives the internal object.

**Comment by markerikson** [comment]
@a-c-sreedhar-reddy : while I don't think it's directly related, that is a _realllly_ weird way to set up a Redux store. It looks like you're mixing pieces of the plain `createStore` function with RTK's `getDefaultMiddleware`. Please don't do that :) Just use `configureStore` - it will do all that setup work for you.  

(Also I'd be interested in hearing, in a separate discussion thread, why you opted you turn off the dev check middleware.)

**Comment by Methuselah96** [comment]
@a-c-sreedhar-reddy
1. Can you try out [Redux DevTools - Next](https://chrome.google.com/webstore/detail/redux-devtools-next/oamphgegmigmlgkdnijmeomjenbmkbdg) as well when you get a chance? I'm 90% your problem is the same, just want to make sure.
2. What are you using `symbol-observable` for? RxJS has a ponyfill for Symbol.observable if I understand correctly.

**Comment by a-c-sreedhar-reddy** [comment]
> 1. Can you try out [Redux DevTools - Next](https://chrome.google.com/webstore/detail/redux-devtools-next/oamphgegmigmlgkdnijmeomjenbmkbdg) as well when you get a chance?

@Methuselah96 Yes it crashed 
![image](https://user-images.githubusercontent.com/16081083/149013362-0277bf4e-40d4-41ae-8e58-f6f98bdfac48.png)

**Comment by Methuselah96** [comment]
@j-dowell @a-c-sreedhar-reddy Just released [v3.0.3](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.3) with a fix. It's released on Firefox and pending review on Chrome (usually review takes a few hours). Until then you can load it unpacked using the ZIP attached to the release. Let me know if it fixes your issue.

@sorinpav Feel free to try the new version as well, but I suspect the issue you're having is caused by something else.

**Comment by a-c-sreedhar-reddy** [comment]
It worked now. Thanks @Methuselah96 ✌🏻

**Comment by robmcm** [comment]
Thanks @Methuselah96 3.0.3 also fixes an issue we were having with accessing the observable manually using symbol-observable. Appreciate the quick turnaround!

**Comment by Methuselah96** [comment]
@markerikson To conclude our earlier conversation, it turns out RxJS [stopped using a polyfill](https://github.com/ReactiveX/rxjs/pull/3387) for Symbol.observable as well which makes me agree that Redux should not be using `symbol-observable` since the original intent of making the Redux store observable was to make the store [interop with RxJS](https://github.com/reduxjs/redux/pull/1632).

The solution of making sure to run polyfills first doesn't work for the extension since the Chrome extension code runs before any user code. I've made it so that the DevTools doesn't resolve Symbol.observable until the user creates a store and it will produce a console warning if Symbol.observable doesn't match between Redux and the DevTools. If a user gets that warning it means that they polyfilled Symbol.observable after importing Redux and before creating a store.

**Comment by sorinpav** [comment]
@Methuselah96 It appears that the 3.0.3 version did not sort our issue. I've tried both the "-next" and the official Redux-devtools extensions. v3.0.3. They don't seem to work for us. Should I start a new issue, or should we reopen this one? Also, could you please re-iterate what details you would need from our config?

**Comment by Methuselah96** [comment]
@sorinpav I think starting a new issue would be preferable since it's a different root issue. If you could specify how you're creating your store similarly to how it was done [here](https://github.com/reduxjs/redux-devtools/issues/1002#issue-1098490023) and [here](https://github.com/reduxjs/redux-devtools/issues/1002#issuecomment-1010297615) that would be great. Thanks!

**Comment by markerikson** [comment]
@Methuselah96 gotcha. Really appreciate your detective work and digging here!
