### ISSUE TITLE
react-json-tree esm exports

### ISSUE THREAD

**Issue by CrOrc** [reduxjs/redux-devtools#1010]
ESM export is broken in react-json-tree@0.16,0.

Now the only export is named export JSONTree.
So imports should be changed from
```jsx
import JSONTree from "react-json-tree"
```
to
```jsx
import { JSONTree } from "react-json-tree"
```

Please, add it to CHANGELOG

**Comment by Methuselah96** [comment]
The release notes are now documented in [Releases](https://github.com/reduxjs/redux-devtools/releases). This particular change is documented [here](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.1). Creating good release notes in monorepos is hard since there are over 20 packages. I tried using conventional commits for a bit, but I didn't think it produced good release notes. I might try https://github.com/changesets/changesets next. I'll keep this open until I decide how to resolve it.

**Comment by Methuselah96** [comment]
Resolved in https://github.com/reduxjs/redux-devtools/commit/8b69d7d40f1a799924d336d70e9cdd71ac0b5bc0.
