### ISSUE TITLE
Doesn't automatically follow state anymore

### ISSUE THREAD

**Issue by taylorwoodman** [reduxjs/redux-devtools#1081]
In the previous version when I'd open my dev tools it'd automatically display the most up to date state object but now I have to click on an action to see what the state is. This makes it so I have to keep clicking actions to keep seeing the most up to date state instead of being able to watch the state object change as I'm dispatching actions

**Comment by musfiqus** [comment]
Same here.

**Comment by GBouffard** [comment]
Same here as well.

**Comment by Methuselah96** [comment]
I'm having trouble reproducing the issue you're describing. When I click on the State tab with no action selection it shows the latest state which keeps updating. Does it show anything for you when you have the State tab selected?

**Comment by mjbour** [comment]
Same here

**Comment by djflorio** [comment]
I've been experiencing the same issue for roughly 1 month. A few weeks ago I uninstalled and reinstalled the extension, and it worked normally for a few weeks before randomly starting this behavior again this morning. I tried reinstalling again, but this time it didn't work.

Here's a gif of the issue. You can see that `workflows/setTotalPageCount` is selected, and when additional actions are fired, the inspector stays locked on `workflows/setTotalPageCount`.

![reduxdevtoolsissue4](https://user-images.githubusercontent.com/10994136/155555984-4bf55d37-ddd0-4fb5-8de9-9f4b673da28e.gif)

Chrome Version 98.0.4758.102 (Official Build) (64-bit)
Redux DevTools 3.0.9

**Comment by junyi-peng-kr** [comment]
I am facing the same issue here, but it only occurs on the normal mode chrome windows, if I open with incognito mode, the state is always update-to-date.

**Comment by Methuselah96** [comment]
Some diagnostic questions:

- Can you try out [this counter example](https://methuselah96.github.io/redux-devtools-counter-example/) to see if the bug is happening on all Redux applications?
- Does this bug happen for all three of the different ways of opening the Redux DevTools?
  - The Chrome DevTools tab
  - The panel that can be opened through the extensions toolbar
  - The new window that can be opened by clicking one of the "grid" icons in the bottom right
- Does the bug happen in incognito mode?
- Does the "Action" tab show the most recent action?
- Does the bug happen if you disable all other Chrome extensions?
- What operating system are you on?

**Comment by mjbour** [comment]
> I've been experiencing the same issue for roughly 1 month. A few weeks ago I uninstalled and reinstalled the extension, and it worked normally for a few weeks before randomly starting this behavior again this morning. I tried reinstalling again, but this time it didn't work.
> 
> Here's a gif of the issue. You can see that `workflows/setTotalPageCount` is selected, and when additional actions are fired, the inspector stays locked on `workflows/setTotalPageCount`.
> 
> ![reduxdevtoolsissue4](https://user-images.githubusercontent.com/10994136/155555984-4bf55d37-ddd0-4fb5-8de9-9f4b673da28e.gif)
> 
> Chrome Version 98.0.4758.102 (Official Build) (64-bit) Redux DevTools 3.0.9

this solution worked for me, Thank you!

**Comment by djflorio** [comment]
@Methuselah96 

- Can you try out [this counter example](https://methuselah96.github.io/redux-devtools-counter-example/) to see if the bug is happening for all Redux applications?
  - Yes, the bug happens with this example.
- Does this bug happen for all three of the different ways of opening the Redux DevTools?
  - The Chrome DevTools tab
    - Yes
  - The panel that can be opened through the extensions toolbar
    - Yes. Also I'm not sure if this is normal behavior (I haven't used the extension from the toolbar for a long time), but when I click anywhere in the UI, the extension's popout closes, and I have to reopen it to see the action that fired.
  - The new window that can be opened by clicking one of the "grid" icons in the bottom right
    - Yes
- Does the bug happen in incognito mode?
  - Yes
- Does the "Action" tab show the most recent action?
  - No, same issue as the "State" tab.
- Does the bug happen if you disable all other Chrome extensions?
  - Yes
- What operating system are you on?
  - Tested and confirmed to be occurring on:
    - Windows 11 Pro (this started happening while I was on Windows 10 Pro)
    - macOs Monterey 12.0.1
  - I've also just checked on Firefox 97.0.1, and the issue is occurring there for me as well.

**Comment by Methuselah96** [comment]
@djflorio Thanks for the info. If you don't mind, can try:

1. Open the panel through the extensions toolbar.
2. Right-click > Inspect to open the Chrome DevTools for the extension.
3. Go to the Application tab.
4. Expand IndexedDB, click on "localforage - chrome-extensions://lmhk...".
5. Delete database.
6. Close out Chrome and reopen and see if the bug persists.

I'm not sure if this will do anything, just covering my bases.

**Comment by djflorio** [comment]
@Methuselah96 No problem. I performed those steps, and unfortunately there's no change.

**Comment by djflorio** [comment]
@Methuselah96 No problem at all, thanks for digging in and finding the issue! Yep you're right; if I first select an action and then de-select it, the state tree remains up-to-date as more actions are fired.

For some reason I thought that it was supposed to actively highlight the latest action in the list, as well as show the most updated state tree, but this makes more sense; if you have an action highlighted, it makes sense for the UI to lock onto it.

**Comment by PetarKirov** [comment]
> Clicking on the action again which should deselect it and cause the Redux DevTools track the current state.

That was the solution for me as well.

@Methuselah96 I (like I presume others experiencing this issue) didn't know that it was possible to deselect the selected action simply by clicking on it. What I tried (and what I thought was the most logical) was to click on the empty space below the last action, as in most UI list implementations that usually deselects (all) selected items.

**Comment by Methuselah96** [comment]
Frankly, I didn't know either until looking at the source code. Happy to accept PRs to improve the situation, I don't have as much time for open-source these days.

**Comment by sehrish30** [comment]
Updating @redux-devtools/extension worked for me

**Comment by banderberg** [comment]
I don't know what they did but this big update essentially ruined what used to be a great tool..

**Comment by Methuselah96** [comment]
It looks like there are still some cases where this is an issue even with the changes in the attached PR. Need to look into this again some more.

**Comment by joemart** [comment]
I'm also experiencing the same issues

**Comment by ozkoidi** [comment]
Similar issue here, the extension used to work some time ago. When I tried today (on Chrome 100.0.4896.88) I don't see any logs or actions and state is `undefined`.

![image](https://user-images.githubusercontent.com/42638799/170048777-214e1015-1211-4f80-9644-3cf855ad68cc.png)

- I can't use the workaround of clicking an action because there are no actions.
- I don't have anything on indexDB
- I deleted the extension an re-installed but the issue persists.
- On Firefox (with the version 3.0.11 of the extension) I get the message : No store found. Make sure to follow the instructions

![image](https://user-images.githubusercontent.com/42638799/170049446-5f6754fc-ffea-4c9b-98ae-4ee40c9c02a7.png)

**Comment by ozkoidi** [comment]
@rgutt, is working again for me.
The problem in my case was that on my Angular app the import of `StoreDevtoolsModule.instrument()` on _ra-app.module.ts_ was moved up within the list.
Once I put it back on the last position of the `imports` array of the `NgModule` (after the import of `StoreModule.forRoot()`) I was able to see the actions and the state again in the Redux Chrome extension.

**Comment by philipjc** [comment]
I've also experienced this today. For me turning off the extension and closing the tab, starting a new tab and turning the extension back on worked for me. I think it started when I started interacting with the Action tab, so I am going to leave it alone :)

**Comment by asiby** [comment]
I was about to suggest the same thing as @philipjc. It could help everyone if the state of the tool is prominently displayed using a ribbon of some sort. Or, there could be an obvious button named `Follow Recent Action` which will simply deselect any action.

**Comment by olgazh565** [comment]
I had the same issue - the State tab did not show any state updates while the Action tab worked as expected. The solution turned out to be very simple for me - I clicked on the 'Log monitor' tab at the bottom panel of the tool and then back on the 'Inspector' tab, and the state was shown again on the State tab. Hope it might help to someone else as well.
