### ISSUE TITLE
Redux Dev Tools Stopped Working

### ISSUE THREAD

**Issue by gerstej9** [reduxjs/redux-devtools#1091]
I recently noticed the redux dev tools icon is no longer green and is greyed out when pinned to my chrome browser. It also no longer seems to work. Actions do not seem to be recorded and the theme has changed. This was a very helpful tool but I cannot use it anymore as things stand. Any suggestions?
Thank you

**Comment by Methuselah96** [comment]
Is it possible that you're using the deprecated `window.devToolsExtension`? `window.devToolsExtension` was [renamed](https://github.com/reduxjs/redux-devtools/tree/main/extension#usage) to `window.__REDUX_DEVTOOLS_EXTENSION__` / `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.

**Comment by gerstej9** [comment]
Thank you for getting back to me so quickly 
Here is some of the code

`import { createStore, applyMiddleware, Store, combineReducers, compose } from "redux"
import { composeWithDevTools } from "redux-devtools-extension"

const composeFunction = LOGGING_DEV_TOOLS ? composeWithDevTools : compose

const createStoreWithMiddleware = composeFunction(
  applyMiddleware.apply(this, [sagaMiddleware, ...sitkaMeta.middleware, ...middleWares]),
)(createStore)
`

I'm not seeing anything in my code that utilizes the window.devToolsExtension

Do you see anything with the above code that sticks out to you?

**Comment by markerikson** [comment]
@gerstej9 while this is totally unrelated to your actual question, I _will_ say that that is an extremely outdated way of calling `createStore` :)  You haven't had to do `applyMiddleware()(createStore)` since [Redux 3.1.0 in January 2016](https://github.com/reduxjs/redux/releases/tag/v3.1.0) :)  There also isn't a need to do `applyMiddleware.apply()`.

If I was going to rewrite that with just the Redux core, I'd do:

```js
const middlewareEnhancer = composeFunction(applyMiddleware(sagaMiddleware, ...sitkaMeta.middleware, ...middlewareWares));
const store = createStore(rootReducer, middlewareEnhancer);
```

Or, even better, with Redux Toolkit's `configureStore`:

```js
const store = configureStore({
  reducer: rootReducer,
  middleware: [sagaMiddleware, ...sitkaMeta.middleware, ...middlewareWares],
  devTools: LOGGING_DEV_TOOLS
})
```

In fact, I'm curious: if you switch over to RTK and `configureStore` as shown, does this issue still happen?

**Comment by gerstej9** [comment]
Thank you Mark, I'm working on a legacy code base and fairly new to it but that looks like a great suggestion. I will try to implement that when I can and see if it solves the problem. Much appreciated!

**Comment by anton-sementsov** [comment]
HI, guys. I have the same problem, few days ago Redux devTools stop to show state. 

`const store = configureStore({
  reducer: {
    auth,
    ....
    notifications,
    county,
  },
  middleware: getDefaultMiddleware({
    serializableCheck: false,
  }),
  devTools: true,
});`
