### ISSUE TITLE
Set() is displaying as {  }

### ISSUE THREAD

**Issue by IrwinJuice** [reduxjs/redux-devtools#1169]
Hi,
In Redux DevTools version 3.0.11 'Set()' is displaying as { }
Is it Ok, or this is a bug? I have never used this tool befoure.

![image](https://user-images.githubusercontent.com/17815703/168808345-1cc7923e-1f79-4aae-9855-184ec08cf563.png)

consol.log to show that Set of roles has values.
![image](https://user-images.githubusercontent.com/17815703/168808494-30c8207f-84af-4ce2-a502-f65e0f7a5eb0.png)

**Comment by Methuselah96** [comment]
In order to view `Set`s and `Map`s you need to enable the [`serialize` option](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md#serialize) (set `options` to `true`). Note that the Redux Style Guide [suggests not putting `Set`s and `Map`s in state](https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions).

**Comment by IrwinJuice** [comment]
Thank you!

**Comment by KovDimaY** [comment]
Hi, @Methuselah96! I would like to know why this serialize configuration is disabled by default? Does it have any danger or drawbacks to having it enabled? Thanks in advance!
