### ISSUE TITLE
why not expose a api like `disable()` to exclude in production 

### ISSUE THREAD

**Issue by Genffy** [reduxjs/redux-devtools#327]
i know there is a way to achieve that [exclude-devtools-from-production-builds](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds)
but i think that is so complex for a component
so why not expose a api like `disable()` to disable it ?

**Comment by zalmoxisus** [comment]
The idea is to remove this part completely from the production build, that's why it's so complex (as you have to strip also react components).

A simpler approach is to use the browser extension, which doesn't include any components, so you can just use:

```js
import { createStore } from 'redux';
import { devToolsEnhancer } from 'redux-devtools-extension/developmentOnly';

const store = createStore(reducer, /* preloadedState, */ devToolsEnhancer());
```

It takes care of `process.env.NODE_ENV !== 'production'` [out of the box](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/developmentOnly.js#L18). Also you could even keep the extension's enhancer in production. See [the Extension's Readme](https://github.com/zalmoxisus/redux-devtools-extension#15-using-in-production) for more options.
