### ISSUE TITLE
Out of local storage while writing debug state in Chrome

### ISSUE THREAD

**Issue by BrianHanechak** [reduxjs/redux-devtools#332]
Chrome appears to limit local storage to 5MB. My application has some state objects that quickly grow well above that. Would it be possible to use a different method of storage, like perhaps IndexedDB? Or, perhaps, compress the JSON that gets put into storage and decompress on retrieval?

Part of the issue is that my application has potentially large objects and supports undo/redo, so it's possible I can also improve this by writing custom serialization (although that seems like it might be tricky to write.)

**Comment by zalmoxisus** [comment]
AFAIK, the limit for local storage depends on how much space you have available on the the primary disk.

Since you noticed that you're using the extension, we've added the ability to persist the state right from there, without need for local storage. It solves also other issues that `persistState` enhancer has. See https://github.com/zalmoxisus/redux-devtools-extension/pull/276 and related issues.

That said, we'll not include `persistState` enhancer in Redux DevTools Extension `3.0` anymore.

**Comment by BrianHanechak** [comment]
This is very cool! But, it doesn't seem like this is running my de-serializing code... if I use this persist state toggle, all of my arrays are converted to regular JavaScript arrays instead of Immutable.js lists.

Is there a different parameter I should pass for a custom deserializer for state persisted in the extension? Or am I missing something else?

**Comment by zalmoxisus** [comment]
As mentioned in #330, it was broken for persisting and import. Will publish the fix soon, just want to see if I can provide a out of the box function to handle Immutable, as just `toJS` / `fromJS` [wouldn't handle all the cases](https://github.com/gaearon/redux-devtools/issues/108).

Track https://github.com/zalmoxisus/redux-devtools-extension/issues/278#issuecomment-270619376. Thanks for investigating it.
