### ISSUE TITLE
How can I get this new awesome looking UI?

### ISSUE THREAD

**Issue by suhailibnnisar** [reduxjs/redux-devtools#503]
Where and how can I get new cool UI as shown in this repo's readme, is it a standalone app or something else.
![Screenshot from 2020-03-06 17-54-34](https://user-images.githubusercontent.com/61163044/76082593-df75d100-5fd3-11ea-8ad1-6505c6358ab1.jpg)

**Comment by Methuselah96** [comment]
The new UI has yet to be released. As far as I know, the new UI is ready to go since the changes in https://github.com/zalmoxisus/remotedev-app/pull/30 were included in https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-core, however the changes have not yet been published. Once we get a little more organized in this repo, we can look into what still needs to be done before we can publish a new release of the Redux DevTools extensions.

**Comment by Methuselah96** [comment]
It has been released in v3 of the extension.
