### ISSUE TITLE
"redux-devtools-extension" gets laggy and eventually crashes when I try to open it.

### ISSUE THREAD

**Issue by bhatvikrant** [reduxjs/redux-devtools#643]
As soon as I click on the redux dev tools extension in chrome & firefox after some actions are dispatched the extension becomes unresponsive and the browser window freezes. 

I checked out issue #347 and tried to find how to set maxAge, but was unable to find how to set maxAge for [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm)

My store.js file looks like this:
```js
import { createStore, applyMiddleware } from "redux";
import thunk from "redux-thunk";
import { composeWithDevTools } from "redux-devtools-extension";
import rootReducer from "./rootReducer";

const store = createStore(
  rootReducer,
  composeWithDevTools(applyMiddleware(thunk))
);

export default store;

```

Is there already a fix for this? Thanks for your time 🙂

**Comment by Methuselah96** [comment]
If you're using the extension, then the issue is most likely [the amount of data that has to be serialized](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu). Do you have a lot of data in your store?

One option to fix that would be to [manually integrate redux-devtools as a component](https://github.com/reduxjs/redux-devtools/blob/master/docs/Walkthrough.md#manual-integration) into your app. This would avoid on the huge amount of serialization between your app and the extensions that usually causes performance issues.

**Comment by bhatvikrant** [comment]
@Methuselah96 yes, I do have quite some data in my store. 
Is it worth adding redux as a component? I mean I just use redux dev tools for development and not in production

**Comment by Methuselah96** [comment]
@bhatvikrant It's up to you, but there is a way to [exclude it from your production build](https://github.com/reduxjs/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds).

**Comment by bhatvikrant** [comment]
Okay, thanks for the help! @Methuselah96

**Comment by Methuselah96** [comment]
No problem!
