### ISSUE TITLE
Unchecked runtime.lastError: "sync" is not available in this instance of Chrome

### ISSUE THREAD

**Issue by kaushalyap** [reduxjs/redux-devtools#696]
I am using redux-devtools with electron using https://github.com/MarshallOfSound/electron-devtools-installer
But in console I am getting following, error goes away when I remove redux-devtools 

```
Unchecked runtime.lastError: "sync" is not available in this instance of Chrome
Error handling response: TypeError: Cannot read property 'filter' of undefined
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/content.bundle.js:1:21235
```

**Comment by Methuselah96** [comment]
Looks like there is also an issue for this on the `electron-devtools-installer` repo as well: https://github.com/MarshallOfSound/electron-devtools-installer/issues/160.

**Comment by kaushalyap** [comment]
@Methuselah96 But I think issue is in this extension since react dev tools works fine.

**Comment by Methuselah96** [comment]
@kaushalyap Yeah, that's quite possible, I was just linking to the other issue so that there's discoverability between the two issues.

**Comment by Slapbox** [comment]
Seeing the same error. Oddly it's only in one of our windows, and even more oddly the devtools seem to work fine.

**Comment by zhuhaow** [comment]
I located the error at https://github.com/reduxjs/redux-devtools/blob/a094e3b42cdeab75eb5fdbe56e6b7ad784c01ab3/extension/src/browser/extension/options/syncOptions.js#L32-L56

I notice the extension is polyfilling the `chrome.storage.sync` for electron. I wonder if this error is because of the code here https://github.com/reduxjs/redux-devtools/blob/a094e3b42cdeab75eb5fdbe56e6b7ad784c01ab3/extension/src/browser/extension/options/syncOptions.js#L86-L94 actually sends the code to another process that is not polyfilled?

**Comment by zhuhaow** [comment]
Create #711 for this.

**Comment by zhuhaow** [comment]
@Methuselah96 Can you take a look?

**Comment by Methuselah96** [comment]
Yeah, it's on my list to review. Looks good from a glance, just want to double-check the context.

**Comment by Methuselah96** [comment]
Are you seeing the following error message:

```
Unchecked runtime.lastError: "sync" is not available in this instance of Chrome
```

Or is Redux DevTools just not working on Electron for you?
