### ISSUE TITLE
Installing the latest version of this package results in yarn warnings about workspaces

### ISSUE THREAD

**Issue by kaiyoma** [reduxjs/redux-devtools#854]
After reinstalling the latest version of this package, I'm starting to see warnings during yarn install:

```
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
```

If I search through my node_modules, I can find the offending files:

```
$ find node_modules/ -name package.json | xargs grep workspaces
node_modules/@redux-devtools/app/node_modules/react-redux/package.json:  "workspaces": [
node_modules/@redux-devtools/core/node_modules/react-redux/package.json:  "workspaces": [
```

What's interesting is that we also use react-redux directly, but that package.json doesn't have `workspaces` set, so redux-devtools seems to be at fault here somehow.

**Comment by Methuselah96** [comment]
This issue is with the latest version of `react-redux` ([7.2.5](https://github.com/reduxjs/react-redux/releases/tag/v7.2.5)) so you should open this issue there instead. I'm going to go ahead and close this since it doesn't seem to be an issue on our end, but feel free to let me know if I should reopen it.
