### ISSUE TITLE
[bug] ERESOLVE: Unable to resolve dependency tree

### ISSUE THREAD

**Issue by AnthoniG** [reduxjs/redux-devtools#984]
Just started a new react project and tried to install redux-devtools but I keep getting an  ERESOLVE error
It seems to be something to with my react version.

Current react installed = ^17.0.2
Below is the the error I get
`npm ERR! While resolving: rvwz-rdx@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from redux-devtools@3.7.0
npm ERR! node_modules/redux-devtools
npm ERR!   dev redux-devtools@"*" from the root project
npm ERR! 
`

How do I resolve this apart from dropping the version of react down to 16 ?

**Comment by markerikson** [comment]
What package are you trying to install, exactly, and to do what?

There's a few different things going on here:

- There _is_ technically a `redux-devtools` package ( https://www.npmjs.com/package/redux-devtools ), but it's a component that you'd add to your actual app. That's been deprecated for a while and you shouldn't be installing it.  Instead you should be using the DevTools browser extension
- Even if you _did_ install the `redux-devtools` package, all it's saying is that it works with any of the recent major versions of React.  React 17 isn't explicitly listed, but in practice it would work fine.
- However, the `npm` package manager now tries to install all peer dependencies as of NPM 7, and it's failing because you have React 17 installed and this only says it works with React 16.

So, I think the short answer here is you _shouldn't_ be using the `redux-devtools` package if what you want to do is inspect the behavior of your app as it runs - use the browser extension.

**Comment by AnthoniG** [comment]
Ohh right. For some reason I thought I needed this package to talk to the browser extension.
It has been a while since I played about with Redux. So I am either miss remembering things or getting things totally wrong.

Thanks for the advice. Much appreciated.
Can safely close this now.

**Comment by markerikson** [comment]
Yeah, RTK's `configureStore` will automatically set up the DevTools Extension integration for you, no further work needed:

https://redux.js.org/tutorials/quick-start
